name: keanggotaan
description: Keanggotaan app
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  bloc: ^8.1.4
  dartz: ^0.10.1
  dio: ^5.8.0+1
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_localizations:
    sdk: flutter
  get_it: ^8.0.3
  go_router: ^15.1.1
  injectable: ^2.5.0
  intl: ^0.19.0
  shared_preferences: ^2.5.3

dev_dependencies:
  bloc_test: ^9.1.7
  build_runner: ^2.4.15
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.7.0
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/mocks/get_identity_response.json
    - assets/mocks/get_profile_response.json
    - assets/mocks/login_response.json
    - assets/mocks/update_profile_response.json
    - assets/mocks/update_identity_response.json
